<?php
/**
 * @file
 * Code for the luggage_admin feature.
 */

include_once 'luggage_admin.features.inc';

/*
 * Implements hook_form_FORMID_alter()
 */
function luggage_admin_form_views_exposed_form_alter(&$form, &$form_state) {

  if ($form_state['view']->current_display == "luggage_content") {

    global $user;

    // If the current user doesn't have administer content permissions.
    if (!user_access('administer content')) {
      // Disable the author field and make it default to their own content.
      $form['name']['#disabled'] = TRUE;
      $form['name']['#default_value'] = $user->name;
    }

    // $form['name']['#default_value'] does not work for some reason with
    // $_GET forms.
    // See https://www.drupal.org/node/635242

    if (isset($_GET['name'])) {
      // If name is defined, and the user doesn't have content editor, reset
      // name to the current user.
      if (!user_access('administer content')) {
        $form_state['input']['name'] = $user->name;
      }
    }
    else {
      // If name is not defined, set the default to the current user.
      $form_state['input']['name'] = $user->name;
    }
  }
}


/*
 * Implements hook_views_pre_render()
 */
function luggage_admin_views_pre_render(&$view) {
  // Add an 'Add Content' link to the header.
  $view->header['area']->options['content'] .= t('<a href="@url">Add Content</a><br />', array('@url' => 'node/add'));

  // If the user has administer content permission add an
  // 'Administer All Content' and 'Administer My Content' links to the view's
  // header.
  if ($view->name == "luggage" && $view->current_display == "luggage_content") {
    if (user_access('administer content')) {
      $path = $view->display_handler->options['path'];
      $path_query = array(
        'Published' => "All",
        'type' => "All",
        'title' => "",
        'name' => "",
      );
      $url = url($path, array('query' => $path_query));
      $view->header['area']->options['content'] .= t('<a href="@url">Administer All Content</a><br />', array('@url' => $url));
      $view->header['area']->options['content'] .= t('<a href="@url">Administer My Content</a>', array('@url' => $path));
    }
  }
}
